### Login
GET https://puclaro.ucn.cl/eross/avance/login.php?email=juan@example.com&password=1234

### Avance de un estudiante
GET https://puclaro.ucn.cl/eross/avance/avance.php?rut=333333333&codcarrera=8266


### Malla de una carrera
GET https://losvilos.ucn.cl/hawaii/api/mallas?8606-202320
X-HAWAII-AUTH: jf400fejof13f