#!/bin/sh
export WATCHPACK_POLLING=true
export WATCHPACK_POLLING_INTERVAL=500
export CHOKIDAR_USEPOLLING=true
export CHOKIDAR_INTERVAL=500

echo "Starting Next.js with polling enabled..."
echo "WATCHPACK_POLLING=$WATCHPACK_POLLING"
echo "WATCHPACK_POLLING_INTERVAL=$WATCHPACK_POLLING_INTERVAL"
echo "CHOKIDAR_USEPOLLING=$CHOKIDAR_USEPOLLING"
echo "CHOKIDAR_INTERVAL=$CHOKIDAR_INTERVAL"

exec next dev --turbopack -p 3001

