import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Planifica UCN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
        <Script
          id="hide-nextjs-devtools"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                function hideNextjsDevTools() {
                  // Eliminar el script que crea el overlay de devtools
                  const devOverlayScript = document.querySelector('script[data-nextjs-dev-overlay="true"]');
                  if (devOverlayScript) {
                    devOverlayScript.remove();
                  }
                  
                  // Eliminar el portal de Next.js
                  const portal = document.querySelector('nextjs-portal');
                  if (portal) {
                    portal.remove();
                  }
                  
                  // Eliminar el indicador de devtools
                  const indicator = document.getElementById('devtools-indicator');
                  if (indicator) {
                    indicator.remove();
                  }
                  
                  // Buscar y eliminar el botón dentro del Shadow DOM
                  const portals = document.querySelectorAll('nextjs-portal');
                  portals.forEach(portal => {
                    const shadowRoot = portal.shadowRoot;
                    if (shadowRoot) {
                      const button = shadowRoot.querySelector('button[id="next-logo"], button[data-nextjs-dev-tools-button="true"]');
                      if (button) {
                        button.remove();
                      }
                      const indicator = shadowRoot.querySelector('#devtools-indicator');
                      if (indicator) {
                        indicator.remove();
                      }
                    }
                  });
                }
                
                // Ejecutar inmediatamente
                hideNextjsDevTools();
                
                // Usar MutationObserver para detectar cuando se agrega el portal
                const observer = new MutationObserver(function(mutations) {
                  mutations.forEach(function(mutation) {
                    if (mutation.addedNodes.length) {
                      hideNextjsDevTools();
                    }
                  });
                });
                
                if (document.body) {
                  observer.observe(document.body, {
                    childList: true,
                    subtree: true,
                    attributes: false
                  });
                }
                
                // También ejecutar periódicamente
                setInterval(hideNextjsDevTools, 100);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
