import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { CareerSelectionProvider } from "@/context/CareerSelectionContext";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Planifica UCN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CareerSelectionProvider>
            {children}
          </CareerSelectionProvider>
        </AuthProvider>
        <Script
          id="hide-nextjs-devtools"
          strategy="afterInteractive"
          src="/scripts/hide-nextjs-devtools.js"
        />
      </body>
    </html>
  );
}
